# Generated by Django 2.2.10 on 2020-03-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mqchannel_name', models.CharField(max_length=20)),
                ('mqchannel_type', models.CharField(choices=[('queue', 'Point to Point model'), ('topic', 'Pub Sub model')], default='queue', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"restdemo"."mqchannel"',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='MQMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.CharField(max_length=500)),
                ('message_type', models.CharField(choices=[('text/plain', 'text/plain'), ('application/xml', 'application/xml'), ('application/json', 'application/json')], default='application/json', max_length=100)),
                ('mqchannel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mq.MQChannel')),
            ],
            options={
                'db_table': '"restdemo"."mqmessage"',
                'ordering': ('created',),
            },
        ),
    ]
